//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXLanguageCourseApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grades
    {
        public int GradeId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<bool> GradeIsActive { get; set; }
        public string Grade1 { get; set; }
        public string Grade2 { get; set; }
        public Nullable<int> StudentAbsenteeism { get; set; }
        public string Folder { get; set; }
    
        public virtual Classes Classes { get; set; }
        public virtual Student Student { get; set; }
    }
}
