//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXLanguageCourseApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public int ManagerId { get; set; }
        public string ManagerName { get; set; }
        public string ManagerSurname { get; set; }
        public string ManagerUsername { get; set; }
        public string ManagerPassword { get; set; }
        public Nullable<bool> ManagerIsActive { get; set; }
    }
}
